trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: printenv

- script: pwd
- script: git config --global user.email "nelson.mig.l@gmail.com"
- script: git config --global user.name "Dev Ops"


- task: DownloadSecureFile@1
  name: mavenSettings
  inputs:
    secureFile: 'settings.xml'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     goals: 'clean'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     javaHomeOption: 'JDKVersion'
#     mavenVersionOption: 'Default'
#     mavenAuthenticateFeed: false
#     effectivePomSkip: false
#     sonarQubeRunAnalysis: false

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'release:prepare'
    options: '--batch-mode -s $(mavenSettings.secureFilePath)'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)'
    ArtifactName: 'drop'
    publishLocation: 'Container'